### ISSUE TITLE
DBMS_RANDOM.seed generation on SLOB 2.5.4

### ISSUE THREAD

**Issue by WATERS7200** [therealkevinc/SLOB_2.5.4#1]
Hi Kevin,

It's your old shadow Toby Scanlan from VCE/EMC now over at MetLife. Having issues deploying the latest build with what appears like DBMS_RANDOM.seed generation on SLOB 2.5.4. It only creates one user and then fails to proceed further with below error message being generated.

SQL> DECLARE
  2          filler VARCHAR2(128) := 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX';
  3          key   NUMBER;
  4          x1    VARCHAR2(128) := filler;
  5          x2    VARCHAR2(128) := filler;
  6          x3    VARCHAR2(128) := filler;
  7          x4    VARCHAR2(128) := filler;
  8          x5    VARCHAR2(128) := filler;
  9          x6    VARCHAR2(128) := filler;
 10          x7    VARCHAR2(128) := filler;
 11          x8    VARCHAR2(128) := filler;
 12          x9    VARCHAR2(128) := filler;
 13          x10   VARCHAR2(128) := filler;
 14          x11   VARCHAR2(128) := filler;
 15          x12   VARCHAR2(128) := filler;
 16          x13   VARCHAR2(128) := filler;
 17          x14   VARCHAR2(128) := filler;
 18          x15   VARCHAR2(128) := filler;
 19          x16   VARCHAR2(128) := filler;
 20          x17   VARCHAR2(128) := filler;
 21          x18   VARCHAR2(128) := filler;
 22          x19   VARCHAR2(128) := filler;
 23          v_seed VARCHAR2(32) := TO_CHAR(SYSTIMESTAMP,'YYYYDDMMHH24MISSFFFF');
 24
 25          CURSOR c IS SELECT key FROM keys_1001 ORDER BY DBMS_RANDOM.VALUE();
 26
 27  BEGIN
 28
 29          DBMS_RANDOM.seed (val => v_seed);
 30
 31          FOR key IN 1001 .. 10240
 32  10240 LOOP
 33                  INSERT /*+ APPEND */ INTO keys_1001  VALUES (key);
 34                  IF ( MOD( key, 1023 ) = 0 ) THEN
 35                          COMMIT;
 36                  END IF;
 37
 38          END LOOP;
 39          COMMIT;
 40
 41          OPEN  c;
 42          LOOP
 43                  FETCH c INTO key;
 44                  EXIT WHEN c%NOTFOUND;
 45
 46                  IF ( FALSE = TRUE ) THEN
 47                          x1  := dbms_random.string('X', 128 );
 48                          x2  := dbms_random.string('X', 128 );
 49                          x3  := dbms_random.string('X', 128 );
 50                          x4  := dbms_random.string('X', 128 );
 51                          x5  := dbms_random.string('X', 128 );
 52                          x6  := dbms_random.string('X', 128 );
 53                          x7  := dbms_random.string('X', 128 );
 54                          x8  := dbms_random.string('X', 128 );
 55                          x9  := dbms_random.string('X', 128 );
 56                          x10 := dbms_random.string('X', 128 );
 57                          x11 := dbms_random.string('X', 128 );
 58                          x12 := dbms_random.string('X', 128 );
 59                          x13 := dbms_random.string('X', 128 );
 60                          x14 := dbms_random.string('X', 128 );
 61                          x15 := dbms_random.string('X', 128 );
 62                          x16 := dbms_random.string('X', 128 );
 63                          x17 := dbms_random.string('X', 128 );
 64                          x18 := dbms_random.string('X', 128 );
 65                          x19 := dbms_random.string('X', 128 );
 66                  END IF;
 67
 68
 69
 70          INSERT /*+ APPEND */ INTO cf1 VALUES (key,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19 );
 71          IF ( MOD( key, 31 ) = 0 ) THEN
 72                  COMMIT;
 73          END IF;
 74
 75          END LOOP;
 76          COMMIT;
 77          CLOSE c;
 78  END;
 79  /

Table created.

10240 LOOP
*
ERROR at line 32:
Elapsed: 00:00:00.01
SQL> ORA-06550: line 32, column 1:

SQL> PLS-00103: Encountered the symbol "10240" when expecting one of the following:
DECLARE
* & - + / at loop mod remainder rem <an exponent (**)> ||
multiset
  2  The symbol "*" was substituted for "10240" to continue.

.......

SQL> EXIT;
Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
FATAL   : 2021.07.17-01:34:29 :
FATAL   : 2021.07.17-01:34:29 : f_concurrent_table_load: Concurrent base table load failure
FATAL   : 2021.07.17-01:34:29 :
FATAL   : 2021.07.17-01:34:29 :
FATAL   : 2021.07.17-01:34:29 : f_setup_base_table: User user1 table created but concurrent load procedure has failed
FATAL   : 2021.07.17-01:34:29 :
FATAL   : 2021.07.17-01:34:29 :
FATAL   : 2021.07.17-01:34:29 : f_setup: Failed to load user1 SLOB table
FATAL   : 2021.07.17-01:34:29 :

**Comment by WATERS7200** [comment]
31 FOR key IN 1001 .. 10240
32 10240 LOOP => something odd with the redundant 10240

Here's my SLOB.conf (I actually modified your source code and I'm trying to get it to run for Oracle 11.2.0.4 on AIX 7.2)
Appears to be working apart from line 32 above ... something with the loop or DBMS_RANDOM.seed generation.

axrsgpar0335(oracle):ORCL112:/home/oracle/SLOB>more slob.conf
#### SLOB 2.5.4.0 slob.conf

SCAN_PCT=0
SCALE=10240
WORK_LOOP=0
RUN_TIME=300
WORK_UNIT=64
UPDATE_PCT=10
SCAN_TABLE_SZ=1M
REDO_STRESS=LITE
THREADS_PER_SCHEMA=2
LOAD_PARALLEL_DEGREE=2
DATABASE_STATISTICS_TYPE=awr   # Permitted values: [statspack|awr]

#######################################
#### Settings for SQL*Net connectivity:
#### Uncomment the following if needed:
#######################################
ADMIN_SQLNET_SERVICE="ORCL112"
SQLNET_SERVICE_BASE="ORCL112"
#SQLNET_SERVICE_MAX="1"

#### Note: Admin connections to the instance are, by default, made as SYSTEM
#          with the default password of "manager". If you wish to use another
#          privileged account (as would be the case with most DBaaS), then
#          change DBA_PRIV_USER and SYSDBA_PASSWD accordingly.
#### Uncomment the following if needed:
#DBA_PRIV_USER="system"
SYSDBA_PASSWD="welcome1"

#### The EXTERNAL_SCRIPT parameter is used by the external script calling feature of runit.sh.
#### Please see SLOB Documentation at https://kevinclosson.net/slob for more information
#EXTERNAL_SCRIPT=""

#########################
#### Advanced settings:
#### The following are Hot Spot related parameters.
#### By default Hot Spot functionality is disabled (DO_HOTSPOT=FALSE).
#HOTSPOT_MB=8
#DO_HOTSPOT=FALSE
#HOTSPOT_FREQUENCY=3
#HOTSPOT_OFFSET_MB=16

##########################################################
#### The following controls operations on Hot Schema
#### Default Value: 0. Default setting disables Hot Schema
##########################################################
#HOT_SCHEMA_FREQUENCY=0

#############################################################
#### The following parameters control think time between SLOB
#### operations (SQL Executions).
#### Setting the frequency to 0 disables think time.
#############################################################
#THINK_TM_FREQUENCY=0
#THINK_TM_MIN=.1
#THINK_TM_MAX=.5

**Comment by rdktutorial** [comment]
Hi Tony,

  Sorry. No idea. I've never tested SLOB on AIX.  I have tested SLOB ***connected*** to AIX many times.  I recommend you run client/server by using a linux driver box/VM to drive AIX over SQLNet.  Note, SLOB **does not communicate over SQLNet during the run.  All execution during the run is on the backend.

**Comment by rdktutorial** [comment]
Wait. I've found a bug that is probably related.  Find the assignment to BLOCK_SZ and change it to 8192 or set SCALE to a differed value like 256M or something as a test then let me know.

**Comment by WATERS7200** [comment]
Hi Kevin,

I converted the /bin/bash on AIX and made one small mod to the native AIX grep to make it GNU compatible to make the driver setup.sh shell script run properly but it gets hung up below on the setsize="$SCALE" (modification) and generates the below error message.

setsize="$SCALE"
#setsize = ($SCALE / $threads)

for (( x=0 ; $x < $threads ; x++ ))
do
        (( b = ( $x * $setsize ) +  1  ))
        (( e = ( $x + 1 ) * $setsize ))

        # Deal with the remainder:
        if [ "$x" -eq $(( threads - 1 )) ]
        then
                e="$SCALE"
        fi

        sqlfile="ins_${x}.sql"
        if ( ! f_gen_basetable_sql "$tablespace" "$b" "$e" "$sqlfile" "$obfuscate"  >> $LOG 2>&1 )
        then
                f_msg FATAL ""
                f_msg FATAL "${FUNCNAME}: Concurrent load table setup failure"
                f_msg FATAL ""

                return 1
        fi
done

axrsgpar0335(oracle):ORCL112:/home/oracle/SLOB>./setup.sh IOPS 64
64
NOTIFY  : 2021.07.19-08:28:06 : Begin SLOB 2.5.4.0 setup.
NOTIFY  : 2021.07.19-08:28:06 : ./setup.sh will use SQL*Net connection to create and load via tnsnames.ora service: ORCL112
NOTIFY  : 2021.07.19-08:28:06 : ./setup.sh will connect as "system" with password "welcome1"
NOTIFY  : 2021.07.19-08:28:06 : ADMIN_CONNECT_STRING: "system/welcome1@ORCL112"
NOTIFY  : 2021.07.19-08:28:06 : Load parameters from slob.conf:

SCALE: 100M (12800
12800 blocks)
SCAN_TABLE_SZ: 1M (128
128 blocks)
LOAD_PARALLEL_DEGREE: 2
ADMIN_SQLNET_SERVICE: "ORCL112"
SYSDBA_PASSWD: "welcome1"
DBA_PRIV_USER: "system"

Note: setup.sh will use the following connect strings as per slob.conf:
        Admin Connect String: "system/welcome1@ORCL112"
        Non-Admin Connect String: "@ORCL112"

NOTIFY  : 2021.07.19-08:28:06 : Testing listener status via tnsping to slob.conf->ADMIN_SQLNET_SERVICE ("ORCL112")
NOTIFY  : 2021.07.19-08:28:06 : Testing Admin connect using "sqlplus -L system/welcome1@ORCL112"
NOTIFY  : 2021.07.19-08:28:07 : Dropping prior SLOB schemas. This may take a while if there is a large number of old schemas.
1
NOTIFY  : 2021.07.19-08:28:07 : Deleted 0 SLOB schema(s).
NOTIFY  : 2021.07.19-08:28:07 : Previous SLOB schemas have been removed
NOTIFY  : 2021.07.19-08:28:07 : Preparing to load 64 schema(s) into tablespace: IOPS
NOTIFY  : 2021.07.19-08:28:07 : Loading user1 schema
FATAL   : 2021.07.19-08:28:10 : Load procedure failed for user1 schema. See /home/oracle/SLOB/cr_tab_and_load.out

NOTIFY  : 2021.07.19-08:28:08 : Preparing to load user1 schema
./setup.sh: line 762: ((: b = ( 0 * 12800
12800 ) +  1  : missing `)' (error token is "12800 ) +  1  ")
./setup.sh: line 763: ((: e = ( 0 + 1 ) * 12800
12800 : syntax error in expression (error token is "12800 ")
./setup.sh: line 762: ((: b = ( 1 * 12800
12800 ) +  1  : missing `)' (error token is "12800 ) +  1  ")
./setup.sh: line 763: ((: e = ( 1 + 1 ) * 12800
12800 : syntax error in expression (error token is "12800 ")

**Comment by WATERS7200** [comment]
I only had to change the following grep command with POSIX grep on AIX to make it function as GNU grep natively on AIX.

   +98  if ( ! echo $s |  grep -vE "^-\?[0-9]*$" )

**Comment by rdktutorial** [comment]
All is well that ends well given you are using AIX as the driver :)

**Comment by WATERS7200** [comment]
And SLOB lived happily ever after on a Linux driver VM :)
